version: 2.1

orbs:
  dmi-cci-orb: prod/dmi-cci-orb@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:first"

workflows:
  test-deploy-cci-orb:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Linting and validation
      - orb-tools/lint
      - orb-tools/pack
      # Hold for dev publish
      - approve-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: prod/dmi-cci-orb
          context: "credentials"
          requires: [approve-dev-publish]
      # Trigger an integration workflow to test the dev:${CIRCLE_SHA1} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: integration-tests-dev
          context: "credentials"
          requires:
            - orb-tools/publish-dev
      # Promote production version(s) of the orb.
      - orb-tools/dev-promote-prod-from-commit-subject:
          name: orb-tools/publish-prod
          orb-name: prod/dmi-cci-orb
          context: "credentials"
          requires: 
            - orb-tools/publish-dev
            - integration-tests-dev
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          filters:
            branches:
              only: master





